### ISSUE TITLE
with sufficient files pfind terminates with too many open files error

### ISSUE THREAD

**Issue by carlilek** [VI4IO/pfind#10]
Seen this on two separate storage systems. 

mpirun -np 2304 -ppn 24 -f hostfile-96.1 --bootstrap ssh ./bin//pfind ./datadir-96-24/ -newer ./datadir-96-24//timestampfile -size 3901c -name *01* -N -P -C -s 300 -D rates

using Intel 2018 compiler, 64 or 96 hosts. I don't think it's threadcount related. 

Error output: 
```
[LSOF]
2807

[PFIND EASY]
time: 1553432076.866116810
Fatal error in MPI_Iprobe: Other MPI error, error stack:
MPI_Iprobe(137)..............: MPI_Iprobe(src=MPI_ANY_SOURCE, tag=800, MPI_COMM_WORLD, flag=0x7fff51b80d98, status=0x1) failed
PMPIDI_CH3I_Progress(845)....: fail failed
MPID_nem_tcp_poll(2611)......: fail failed
MPID_nem_tcp_connpoll(2992)..: fail failed
state_listening_handler(3107): accept of socket fd failed - Too many open files
[carlilek@h10u01 io-500-script]$ 
```

Num files is ~36M in the above case (96 clients, 24 threads each), ~37M in another example (64 clients, 64 threads each). ulimit -n is set to 655350 on the client nodes.

**Comment by carlilek** [comment]
Note that with the 64 client/64 thread example, the -N flag was not used.

**Comment by carlilek** [comment]
Also error occurs immediately upon pfind launch.

**Comment by JulianKunkel** [comment]
Was this issue resolved with newer versions Ken?

**Comment by carlilek** [comment]
I believe so, and/or some kind of config fix on my side. I haven’t seen it for ages.

--Ken

Sent from my <advertising redacted>

On Jan 3, 2020, at 11:56 AM, Julian Kunkel <notifications@github.com> wrote:

﻿

Was this issue resolved with newer versions Ken?
