### ISSUE TITLE
Does not compile with gcc10

### ISSUE THREAD

**Issue by markhpc** [VI4IO/pfind#14]
```
/usr/bin/ld: pfind.o:(.bss+0x1c): multiple definition of `pfind_rank'; pfind-main.o:(.bss+0x4): first defined here
/usr/bin/ld: pfind.o:(.bss+0x18): multiple definition of `pfind_size'; pfind-main.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
```

This is due to the GCC10 change to default compile with -fno-common.  There are several ways to fix it, so I haven't submitted a specific fix but am working around it by simply changing compile.sh to explicitly pass in -fcommon.  See:

https://gcc.gnu.org/gcc-10/porting_to.html

**Comment by JulianKunkel** [comment]
Seems to be fixed.
